---
source-git-commit: fd3857e93dbaaf7ffce97715b77ee63e8460af16
workflow-type: tm+mt
source-wordcount: '130'
ht-degree: 0%

---
グラフ LR
サブグラフ CF[&quot;<b>Commerce Foundation</b>&quot;]
方向TB
CS （[&quot;Storefront&quot;]）
CB （[&quot;Backend&quot;]）
終了

    SC （[&quot;Services Connector&quot;]） 
    
     サブグラフ SaaS[&quot;&lt;b>SaaS&lt;/b>&quot;]
    方向TB
    Services （[&quot;&lt;b>Services&lt;/b>&lt;br/>Product Recommendations&lt;br/>Product Recommendations&lt;br/>Catalog Service&lt;br/>Payment Services&quot;]） 
    Integrations （&quot;&lt;b> Integrations&lt;/b>&lt;br/>Data Connection&lt;br/>AEM Assets&quot;]） 
    CF—>&lt;&lt;ph>&lt;&lt;ph> id=&#39;289&#39;/>classDef foundationStyle fill:#FFF9E6,stroke:#C7B88A,stroke-width:3px,color:#000000,rx:15,ry:15,font-family:Adobe Clean
    classDef saasStyle fill:#FFE6F0,stroke:#D4A6B8,stroke-width:3px,color:#000000,rx:15,ry:15,font-family:Adobe Clean&lt;ph=&#39;525&#39;/>classDef boxStyle fill:#FFFFFF,stroke:#000000,stroke-width:2px,color:#000000,rx:15,ry:15,font-family:Adobe Clean
    classDef connectorStyle fill:#4A4A4A,stroke:#4A4A4A,stroke-width:2px,color:#FFFFFF,rx:15,ry:15,font-family:Adobe Clean
    
    class CF foundationStyle&lt;ph=&#39;785&#39;/>class SaaSのスタイル、CS8Box id=&#39;851&#39;/> クラス SC connectorStyle
    
    
    
    
    
    
    
    